# .github/workflows/workflow1.yml
name: Workflow 1

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [ self-hosted, test ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Workflow 1
        run: echo "Running Workflow 1"

      - name: Trigger Workflow 2
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: workflows } = await github.actions.listRepoWorkflows({
            owner: 'aramanji123',
            repo: 'Automation'
            });
            const workflow2 = workflows.workflows.find(w => w.name === 'Workflow 2');
            if (workflow2) {
              await github.actions.createWorkflowDispatch({
                workflow_id: workflow2.id
              });
}
