# .github/workflows/workflow2.yml
name: Workflow 2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [ self-hosted, test ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Workflow 2
        run: echo "Running Workflow 2"
